#!/bin/bash
#
# Nightly regressions for dacapo
#

TOP=$1
CONFIG=$2
REVISION=${3:-HEAD}

if [ -z "$CONFIG" ]; then
  echo "Usage: $0 target-dir config"
  exit 1
fi

RVM_SVNHOME=https://jikesrvm.svn.sourceforge.net/svnroot/jikesrvm
HERE=$(dirname $0)

if [ -z "$BIN" ]; then
  . $HERE/config
fi

#
# Pick up system-specific parameters
#
SYSCONFIG=$BIN/$(uname -m).nightly.config
if [ -e $SYSCONFIG ]; then
  . $SYSCONFIG
fi

(
  cd $TOP
  export JAVA_HOME=$JAVA_HOME_15
  export PATH=$JAVA_HOME/bin:$PATH

  svn co --revision $REVISION $RVM_SVNHOME/rvmroot/trunk rvm_trunk &&
    cd $TOP/rvm_trunk && {

    # Apply jikesrvm patches
    [ ! -e  dacapo.patches ] && touch dacapo.patches
    for patch in $BIN/patches/jikesrvm/*.patch
    do
      if $(grep -vq $patch dacapo.patches); then
        echo "Applying patch $patch"
        patch -p0 <$patch && echo "successful"
        echo $patch >> dacapo.patches
      fi
    done

    ant -Dhost.name=$HOST_TYPE -Dconfig.name=${CONFIG} \
	-Dcomponents.cache.dir=$BIN/downloads \
	profiled-image
    ls -l $TOP/rvm_trunk/dist/${CONFIG}_${HOST_TYPE}/JikesRVM
  }
)
