#!/bin/bash
#

#
# Command line parameters
#
TOP=$1
[ -z "$TOP" ] && {
  echo "Usage: $0 scratch-dir"
  exit 1
}
shift

while [ ! -z "$1" ]; do
  case $1 in 
    clean) rm -rf $TOP/harmony
           ;;
    *) 	   echo "Unrecognized parameter \"$1\""
       	   exit 1
       	   ;;
  esac
  shift
done

#
# Internal parameters
#
BIN=$HOME/dacapo_regressions
VMTOP=$TOP/harmony/working_vm/
export JAVA_HOME=/opt/ibm-java2-i386-50
export PATH=$JAVA_HOME/bin:$PATH

ECJ_DIR=$TOP/harmony/common_resources/depends/jars/ecj_3.3/
export BUILD_CFG=release


build_ant() {
  if [ ! -e $TOP/apache-ant-1.6.5 ]; then (
    echo "Downloading ant"
    cd $TOP
    #wget -c http://www.apache.org/dist/ant/ant-current-bin.zip
    wget -c http://archive.apache.org/dist/ant/binaries/apache-ant-1.6.5-bin.tar.gz
    echo "Unpacking ANT"
    tar -xzf apache-ant-1.6.5-bin.tar.gz
  )
  fi
}

build_common() {
  (
    echo "Building common resources"
    cd common_resources
    ant fetch-depends
  )
}

build_jdktools() {
  (
    echo "Building jdktools"
    cd working_jdktools
    ant fetch-depends
    ant -lib $ECJ_DIR
  )
}

build_classlib() {
  (
    echo "Building class library"
    cd working_classlib
    ant fetch-depends
    ant -lib $ECJ_DIR
  )
}

build_vm() {
  (
    echo "Building the VM"
    BUILD=$VMTOP/build
    cd $BUILD
    cp $BIN/drlvm.properties $BUILD/drlvm.properties

    echo "Updating dependencies"
    chmod +x build.sh
    $BUILD/build.sh update && {
      echo "Building"
      $BUILD/build.sh -lib $ECJ_DIR
    }
  )
}

(
svn co https://svn.apache.org/repos/asf/harmony/enhanced/trunk $TOP/harmony
cd $TOP/harmony

echo "Populating source"
ant populate_source

build_ant
export ANT_HOME=$TOP/apache-ant-1.6.5

build_common
build_jdktools
build_classlib
build_vm
)
