#!/bin/bash
#

#
# Command line parameters
#
TOP=$1
[ -z "$TOP" ] && {
  echo "Usage: $0 scratch-dir"
  exit 1
}
shift

if [ -z "$BIN" ]; then
  . $(dirname $0)/config
fi

while [ ! -z "$1" ]; do
  case $1 in 
    clean) rm -rf $TOP/harmony
           ;;
    *) 	   echo "Unrecognized parameter \"$1\""
       	   exit 1
       	   ;;
  esac
  shift
done

#
# Internal parameters
#
export JAVA_HOME=$JAVA_HOME_15
export PATH=$JAVA_HOME/bin:$PATH

#
# Dependencies
#
DEPENDS=$BIN/downloads
mkdir -p $DEPENDS

ensure() {
  local target=$1
  local source=$2

  wget -c $source -O $target
}

ensure $DEPENDS/ecj_3.3.jar http://archive.eclipse.org/eclipse/downloads/drops/R-3.3-200706251500/ecj.jar

export BUILD_CFG=release

svn co https://svn.apache.org/repos/asf/harmony/enhanced/trunk $TOP/harmony
export ANT_OPTS='-Xms256m -Xmx512m'

( 
  #
  # Build the classlib and VM
  #
    cd $TOP/harmony &&
    ant -lib $DEPENDS -Dauto.fetch=true all
)

