#!/bin/bash
#
# config.
#
# Configuration variables for DaCapo benchmarks.  "source"d into
# the main shell scripts to pick up symbols.
#

#
# Directory where these scripts live
#
export BIN=$HOME/regression

#
# Directory for log files
#
export LOG=$HOME/log

#
# Scratch directory - requires a couple of Gb of space
#
export SCRATCH=$HOME/tmp

#
# Path to a Java 1.4 SDK
#
export JAVA_HOME_14=/usr/lib/j2se/1.4

#
# Path to a Java 1.5 SDK
#
export JAVA_HOME_15=/opt/jdk1.5.0
#export JAVA_HOME_15=/opt/ibm-java2-i386-50

#
# Path to a Java 6 SDK
#
export JAVA_HOME_6=/opt/jdk1.6.0

#
# Current hostname
#
export HOST=$(uname -n)

# 
# JikesRVM configuration variabes
# 
# The host type as used by the JikesRVM build system
#
export HOST_TYPE=$(uname -m | sed -e 's/i686/ia32/' -e 's/x86_64/ia32/')-$(uname -o | sed -e 's@GNU/Linux@linux@')

#
# The JikesRVM configuration to build
#
export RVM_CONFIG=FastAdaptiveGenMS

#
# List of virtual machines
#
export ALL_VMS="DRLVM JIKESRVM SUN JDK16 J9 JROCKIT JROCKIT16 CACAO"

#
# List of virtual machines to do performance runs against
#
export PERF_VMS="JIKESRVM DRLVM SUN JDK16 J9 JROCKIT JROCKIT16 CACAO"

#
# The web server and directory where the results live
#
export PUBLIC_HOST=jikesrvm.anu.edu.au
export PUBLIC_PATH=

#
# Advice files for JikesRVM replay compilation (under development)
#
export ADVICEDIR=$HOME/regression/advice-10-iterations

#
# Do we need to hack the bootclasspath, or are we testing the dacapo classloader ?
#
export HACK_BOOTCLASSPATH=true

#
# Support node-specific overrides
#
[ -e $BIN/config.$HOST ] && . $BIN/config.$HOST

export PUBLIC=$PUBLIC_HOST:$PUBLIC_PATH
