#!/bin/bash

TODAY=$(date +%Y%m%d)
DATE=${1:-$TODAY}
TOP=$HOME/tmp/rerun-drlvm-$DATE

if [ -z "$BIN" ]; then
  . $(dirname $0)/config
fi


mkdir $TOP || { echo "Please cleanup $TOP before you re-run"; exit 1; }

echo "Copying old results back here"
rsync -a $PUBLIC/results-$DATE $TOP/

if [ ! -e $TOP/results-$DATE/summary.dat ]; then
  echo "results-$DATE was not a valid run - perhaps you should redo the whole thing"
  exit 1
fi

if [ ! -e $BIN/builds/dacapo-$DATE.jar ]; then
  echo "There is no dacapo JAR for that date"
  exit 1
fi

(
  cd $TOP
  export DRLVM_HOME=$TOP/harmony/harmony/working_vm/build/lnx_ia32_gcc_release/deploy/jdk
  for try in 1 2 3 LAST
  do
    echo "Building harmony"
    $BIN/build_harmony $TOP/harmony &> $TOP/drlvm.build.log.$try
    if [ -e $DRLVM_HOME/jre/bin/java ]; then 
      break;
    else
      echo "Build failed on try $try"
      if [ "$try" = "LAST" ]; then
        echo "Giving up in disgust"
        exit 1
      fi
    fi
  done

  cp $BIN/builds/dacapo-$DATE.jar .
  $BIN/test_dacapo $DATE DRLVM
  $BIN/test_dacapo_results results-$DATE
)
