#!/bin/bash

set -x
TODAY=$(date +%Y%m%d)

BIN=$HOME/dacapo_regressions
. $BIN/config

DATE=${1:-$TODAY}
SVNDATE=$(date -d $DATE +%Y-%m-%d)
TOP=$HOME/tmp/rerun-rvm-$DATE

[ -e $TOP ] || mkdir $TOP #|| { echo "Please cleanup $TOP before you re-run"; exit 1; }

echo "Copying old results back here"
rsync -a war:pub/dacapo/regression/results-$DATE $TOP/

if [ ! -e $TOP/results-$DATE/summary.dat ]; then
  echo "results-$DATE was not a valid run - perhaps you should redo the whole thing"
  exit 1
fi

if [ ! -e $BIN/builds/dacapo-$DATE.jar ]; then
  echo "There is no dacapo JAR for that date"
  exit 1
fi

(
  cd $TOP
  if [ ! -e $TOP/rvm_trunk/dist/${RVM_CONFIG}_${HOST_TYPE}/JikesRVM ]; then
    for try in 1 2 3 LAST
    do
      echo "Building jikesrvm"
      $BIN/build_jikesrvm $TOP $RVM_CONFIG "{$SVNDATE}" &> $TOP/results-$DATE/jikesrvm.build.$try.log
      if [ ! -e $TOP/rvm_trunk/dist/${RVM_CONFIG}_${HOST_TYPE}/JikesRVM ]; then
        echo "ERROR: JikesRVM failed to build."
        [ -e $RVM_BUILD ] && rm -rf $RVM_BUILD
        echo "Build failed on try $try"
        if [ "$try" = "LAST" ]; then
          echo "Giving up in disgust"
          exit 1
        fi
      else
        break;
      fi
    done
  fi
  cp $BIN/builds/dacapo-$DATE.jar .
  export RVM_ROOT=$TOP/rvm_trunk
  $BIN/test_dacapo $DATE JIKESRVM
  $BIN/test_dacapo_results results-$DATE
)
